### ISSUE TITLE
Crash when update Glide to v4.9

### ISSUE THREAD

**Issue by valkoasd** [esafirm/android-image-picker#196]
After update Glide to v4.9 i can't use the library because occurs an exception and application crashes. This is the log of exception: 
`java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in ...)
 at com.esafirm.imagepicker.features.imageloader.DefaultImageLoader.loadImage(DefaultImageLoader.java:17)
at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:55)
at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:24)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
...`
